config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get  'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  root "items#index"

  resources :users, only: [:show] do
    get 'logout', to: 'users#logout'
    get 'items', to: 'users#items'
    resources :cards, only: [:new, :index, :show] do
      collection do
      # クレジットカード登録
        # post 'pay', to: 'cards#pay'
      # クレジットカード削除
        # delete 'delete', to: 'cards#delete'
      end
    end
  end

  resources :items do
    collection do
      get "get_shipping_way"
      get "category_children"
      get "category_grandchildren"
      get "get_size", defauts: { format: 'json' }
    end
  end


  resources :brands, only: [:index], defaults: {format: 'json'}

  resources :items do
    resource :creditcards do
      member do
        get "buy"
        post "pay"
      end
    end
  end
  resources :creditcards, only: [:new, :create, :destroy, :show]

end

app/models/user.rb
class User < ApplicationRecord
  has_many   :items      , dependent: :destroy
  has_many   :addresses  , dependent: :destroy
  # has_many   :comments   , dependent: :destroy
  # has_many   :favorites  , dependent: :destroy
  # has_many   :evaluations, dependent: :destroy
  has_one   :creditcard, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :nickname, :firstname , :lastname, :firstname_kana, :lastname_kana, :nickname, :birth_year, :birth_month, :birth_day, :tel_number, presence: true
  validates :nickname, :tel_number, :email, uniqueness: true

  validates :firstname     , format: {with: /\A[ぁ-んァ-ン一-龥]/}
  validates :lastname      , format: {with: /\A[ぁ-んァ-ン一-龥]/}
  validates :firstname_kana, format: {with: /\A[ァ-ンー－]+\z/}
  validates :lastname_kana , format: {with: /\A[ァ-ンー－]+\z/}
  validates :birth_year    , format: {with: /\A\d{4}\z/}
  validates :birth_month   , numericality: { only_integer: true , greater_than: 0, less_than: 13 }
  validates :birth_day     , numericality: { only_integer: true , greater_than: 0, less_than: 32 }
  validates :tel_number    , numericality: { only_integer: true }, length: { in: 10..11 }
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    @user = User.new
  end

  # POST /resource
  def create
    @user = User.new(sign_up_params)
    if @user.valid?
      session["devise.regist_data"] = {user: @user.attributes}
      session["devise.regist_data"][:user]["password"] = params[:user][:password]
      @address = @user.addresses.build
      render :new_address
    else
      render :new
    end
  end

  def create_address
    @user = User.new(session["devise.regist_data"]["user"])
    @address = Address.new(address_params)
    
    if @address.valid?
      @user.addresses.build(@address.attributes)
      @user.save
      session["devise.regist_data"]["user"].clear
      sign_in(:user, @user)
    else
      render :new_address
    end
  end

  protected

  def address_params
    params.require(:address).permit(:firstname, :lastname, :post_number, :prefecture, :city, :address, :apartment, :tel_number)
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def index
  end

  def show
  end

  def items
    @items = Item.where("seller_id = #{current_user.id}")
  end

  def logout
  end
    
  private
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_header.html.haml
.header__contents
  .header__contents__main
    .header__contents__main__main-title
      = link_to image_tag("material/logo/logo.png", class:"icon"), "/" 
    .header__contents__main__search_box
      = form_with url: "#", method: :get, local: true do |f|
        = f.text_field :search, class: "input-box", placeholder:"キーワードから探す"
        %button{type: "submit", class:"search-btn"} 
          = image_tag '/assets/icon-search1.png',class: "image"
  .header__contents__navbar
    %ul.list-left
      %li.list-left__category-btn 
        = link_to "カテゴリー", "/", class: "list-btn"
      %li.list-left__brand-btn
        = link_to "ブランド", "/", class: "list-btn"
      %ul.list-right
        %li.list-right__login-btn 
          = link_to "ログイン", "/", class: "list-btn"
        %li.list-right__registration-btn
          = link_to "新規会員登録", "/", class: "list-btn"

app/views/users/_mainbar-card-create.html.haml
.content__main
  %section.content__main__box
    %h5.content__main__box__header クレジットカード情報入力
    = render "creditcards/registration_cardform"

app/views/users/_mainbar-cards.html.haml
.content__main
  %section.content__main__box
    %h5.content__main__box__header 支払い方法
    .content__main__box__inner
      %section.content__main__box__inner__add-card
        - if @card.blank?
          = link_to new_user_card_url, class: "card-registration-btn" do
            = icon('fa', 'credit-card')
            クレジットカードを追加する
        - else
          = link_to "/users/#{current_user.id}/cards/#{current_user.id}", class: "card-registration-btn" do
            = icon('fa', 'credit-card')
            クレジットカード情報を表示する
          -# = link_to creditcard_path(current_user.id), class: "card-registration-btn" do
          -#   = icon('fa', 'credit-card')
          -#   クレジットカード情報を表示する
        -# %section
          .content__main__box__inner__header
            %h6.content__main__box__inner__header__list クレジットカード一覧
          %ul.content__main__box__inner__header__payment-list
            %li
              = form_with url: "#", class: "payjp-form", method: "POST" do |f|
                %figure
                  = image_tag 'material/logo/amex-logomark.gif', alt: 'amex-logomark.gif', height: '30px', width: '35px'
                .payjp-form__info ****12345678
                .payjp-form__info mm/ss
                = f.submit "削除する", class: "remove-btn"
            %li
              = form_with url: "#", class: "payjp-form", method: "POST" do |f|
                %figure
                  = image_tag 'material/logo/jcb-logomark.gif', alt: 'jcb-logomark.gif', height: '30px', width: '35px'
                .payjp-form__info ****12345678
                .payjp-form__info mm/ss
                = f.submit "削除する", class: "remove-btn"
            %li
              = form_with url: "#", class: "payjp-form", method: "POST" do |f|
                %figure
                  = image_tag 'material/logo/Visa-logomark.png', alt: 'Visa-logomark.png', height: '30px', width: '35px'
                .payjp-form__info ****12345678
                .payjp-form__info mm/ss
                = f.submit "削除する", class: "remove-btn"

app/views/users/_mainbar-logout.html.haml
.content__main
  .content__main__box
    = form_with url: "#", class: "logout-form", method: "POST" do |f|
      .logout-form__box
        = link_to destroy_user_session_path, method: :delete, class: "logout-btn" do 
          ログアウト

app/views/users/_mainbar_top.html.haml
.content__main
  %section.content__main__user-info
    = link_to users_profile_path do
      %figure
        = image_tag 'default-statue.jpeg', alt: 'default-statue.jpeg', height: '60px', width: '60px'
      %h2.content__main__user-info__name テストさん
      .content__main__user-info__data
        %div
          評価数
          %span.evaluation
            1000000
        %div
          出品数
          %span.product-number
            3000000
  %section.content__main__notice-todo
    %ul.content__main__notice-todo__tabs
      %li
        = link_to "お知らせ", "#"
        = link_to "やることリスト", "#"
    .content__main__notice-todo__tab-content
      %ul.content__main__notice-todo__tab-content__notice
        %li
          = link_to "お知らせ1", "#", class: "notice-link"
          = link_to "お知らせ2", "#", class: "notice-link"
          = link_to "お知らせ3", "#", class: "notice-link"
          = link_to "一覧を見る", "#", class: "list-link" 
  %section.content__main__history
    %h1.content__main__history__header 購入した商品
    %ul.content__main__history__tabs
      %li
        = link_to "取引中", "#"
        = link_to "過去の取引", "#"
    .content__main__history__tab-content
    %ul.content__main__history__tab-content__pane
      %li
        = link_to "お知らせ5", "#", class: "content__main__history__tab-content__pane__link" 
        = link_to "お知らせ6", "#", class: "content__main__history__tab-content__pane__link"
        = link_to "お知らせ7", "#", class: "content__main__history__tab-content__pane__link"
        = link_to "一覧を見る", "#", class: "content__main__history__tab-content__pane__list" 

app/views/users/_mainber-card-information.html.haml
.content__main
  %section.content__main__box
    %h5.content__main__box__header クレジットカード登録情報
    = render "creditcards/creditcard_information"

app/views/users/_sidebar.html.haml
.content__side
  %nav.content__side__nav
    %ul.content__side__nav__list
      %li.content__side__nav__list__item
        = link_to user_path(current_user.id) do
          マイページ
          = icon('fas', 'chevron-right', class: "arrow-right")
      %li.content__side__nav__list__item
        = link_to "#" do
          やることリスト
          = icon('fas', 'chevron-right', class: "arrow-right")
      %li.content__side__nav__list__item
        = link_to "#" do
          いいね一覧
          = icon('fas', 'chevron-right', class: "arrow-right")    
      %li.content__side__nav__list__item
        = link_to new_item_path do
          出品する
          = icon('fas', 'chevron-right', class: "arrow-right")
      %li.content__side__nav__list__item
        = link_to user_items_path(current_user.id) do
          出品した商品
          = icon('fas', 'chevron-right', class: "arrow-right")    
      %li.content__side__nav__list__item
        = link_to "#" do
          評価一覧
          = icon('fas', 'chevron-right', class: "arrow-right")  
      %li.content__side__nav__list__item
        = link_to "#" do
          お問い合わせ
          = icon('fas', 'chevron-right', class: "arrow-right")      
      %h1.content__side__nav__list__header 設定
    %ul.content__side__nav__list
      %li.content__side__nav__list__item
        = link_to "#" do
          プロフィール
          = icon('fas', 'chevron-right', class: "arrow-right")
      %li.content__side__nav__list__item
        = link_to "#" do
          発送元・お届け先住所変更
          = icon('fas', 'chevron-right', class: "arrow-right")
      %li.content__side__nav__list__item
        = link_to user_cards_path(current_user.id) do
          支払い方法
          = icon('fas', 'chevron-right', class: "arrow-right")
      %li.content__side__nav__list__item
        = link_to user_logout_path(current_user.id) do
          ログアウト
          = icon('fas', 'chevron-right', class: "arrow-right")

app/views/users/card_create.html.haml
-# ヘッダー
%header
  = render 'items/header'

-# パンくずリスト
%nav.bread-crumbs 
  %ul
    %li パンくずリスト

-# メイン部
.main
  .content
    = render 'sidebar'
    = render 'mainbar-card-create'

-# フッター
%footer
  = render 'items/footer'

-# 画面右下の固定アイコン
= render 'items/purchasebtn'

app/views/users/cards.html.haml
-# ヘッダー
%header
  = render 'items/header'

-# パンくずリスト
%nav.bread-crumbs 
  %ul
    %li パンくずリスト

-# メイン部
.main
  .content
    = render 'sidebar'
    = render 'mainbar-cards'

  -# サードビュー
  .main__third-section
    = render 'items/third-section'

-# フッター
%footer
  = render 'items/footer'

-# 画面右下の固定アイコン
= render 'items/purchasebtn'

app/views/users/create.html.haml
.content
  = render 'sidebar'
  .content__main
    %section.content__main__box
      %h3.content__main__box__header クレジットカード情報入力
      .content__main__box__form フォームいれる
.banner
  バナー領域

app/views/users/index.html.haml
-# ヘッダー
%header
  = render 'items/header'

-# パンくずリスト
%nav.bread-crumbs 
  %ul
    %li パンくずリスト

-# メイン部
.main
  .content
    = render 'sidebar'
    = render 'mainbar'

  -# サードビュー
  .main__third-section
    = render 'items/third-section'

-# フッター
%footer
  = render 'items/footer'

-# 画面右下の固定アイコン
= render 'items/purchasebtn'

app/views/users/items.html.haml
-# ヘッダー
%header
  = render 'items/header'

-# パンくずリスト
%nav.bread-crumbs 
  %ul
    %li パンくずリスト

-# メイン部
.main
  .content
    = render 'sidebar'
    = render 'mainbar-items'

  -# サードビュー
  .main__third-section
    = render 'items/third-section'

-# フッター
%footer
  = render 'items/footer'

-# 画面右下の固定アイコン
= render 'items/purchasebtn'

app/views/users/show.html.haml
-# ヘッダー
%header
  = render 'items/header'
  - breadcrumb :mypage
  

-# パンくずリスト
%nav.bread-crumbs 
  %ul
    = render "layouts/breadcrumbs"

-# メイン部
.main
  .content
    = render 'sidebar'
    = render 'mainbar'

  -# サードビュー
  .main__third-section
    = render 'items/third-section'

-# フッター
%footer
  = render 'items/footer'

-# 画面右下の固定アイコン
= render 'items/purchasebtn'

app/views/users/todo.html.haml
.content
  = render 'sidebar'
  .content__main
    %section.content__main__box
      %h3.content__main__box__header やることリスト