config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get  'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  root "items#index"

  resources :users, only: [:show] do
    get 'logout', to: 'users#logout'
    get 'items', to: 'users#items'
    resources :cards, only: [:new, :index, :show] do
      collection do
      # クレジットカード登録
        # post 'pay', to: 'cards#pay'
      # クレジットカード削除
        # delete 'delete', to: 'cards#delete'
      end
    end
  end

  resources :items do
    collection do
      get "get_shipping_way"
      get "category_children"
      get "category_grandchildren"
      get "get_size", defauts: { format: 'json' }
    end
  end


  resources :brands, only: [:index], defaults: {format: 'json'}

  resources :items do
    resource :creditcards do
      member do
        get "buy"
        post "pay"
      end
    end
  end
  resources :creditcards, only: [:new, :create, :destroy, :show]

end

app/models/creditcard.rb
class Creditcard < ApplicationRecord
  belongs_to :user

  validates :customer_id, presence: true
  
end

app/controllers/creditcards_controller.rb
class CreditcardsController < ApplicationController
  require "payjp"
  before_action :set_card
  before_action :set_item, only: [:buy, :pay]


  def show
    if @card.blank?
      redirect_to action: "new"
    else
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @customer_card = customer.cards.retrieve(@card.payjp_id)

      @card_brand = @customer_card.brand
      case @card_brand
      when "Visa"
        @card_src = "visa.png"
      when "JCB"
        @card_src = "jcb.png"
      when "MasterCard"
        @card_src = "master.png"
      when "American Express"
        @card_src = "amex.png"
      when "Diners Club"
        @card_src = "diners.png"
      when "Discover"
        @card_src = "discover.png"
      end

      @exp_month = @customer_card.exp_month.to_s
      @exp_year = @customer_card.exp_year.to_s.slice(2,3)
    end
  end


  def new
    @card = Creditcard.where(user_id: current_user.id)
    redirect_to creditcard_path(current_user.id) if @card.exists?
  end

  def create
    #credential.ymlに登録したpayjpのapiキーの取得
    Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
    #falshメッセージを導入しているため、後ほど実装
    if params['payjp_token'].blank?
      redirect_to action: "new", alert: "クレジットカードを登録できませんでした。"
    else
      customer = Payjp::Customer.create(
      email: current_user.email,
      card: params['payjp_token'],
      metadata: {user_id: current_user.id}
      )
      @card = Creditcard.new(user_id: current_user.id, customer_id: customer.id, payjp_id: customer.default_card)

      if @card.save
      else
        redirect_to action: "create"
      end
    end
  end

  def destroy
    if @card.blank?
      redirect_to action: "new"
    else
      Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
      customer = Payjp::Customer.retrieve(@card.customer_id)

      customer.delete
      @card.delete
      if @card.destroy
        redirect_to action: "new"
      else
        redirect_to creditcard_path(current_user.id), alert: "削除できませんでした。"
      end
    end

  end

  # 商品購入確認ページをbuyアクションと定義して行う。

  def buy
    @images = @item.images.all
    
    @address = Address.find(current_user.id)
    if @item.seller == User.find(current_user.id)
      redirect_to item_path(@item.id), alert: "あなたが出品した商品です"
    else
      if @item.buyer.present?
        redirect_to item_path(@item.id), alert: "売り切れています"
      else
        if user_signed_in?
          @user = current_user

          if @user.creditcard.present?
            Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
            @card = Creditcard.find_by(user_id: current_user.id)
            customer = Payjp::Customer.retrieve(@card.customer_id)
            @customer_card = customer.cards.retrieve(@card.payjp_id)

            @card_brand = @customer_card.brand
            case @card_brand
            when "Visa"
              @card_src = "visa.png"
            when "JCB"
              @card_src = "jcb.png"
            when "MasterCard"
              @card_src = "master.png"
            when "American Express"
              @card_src = "amex.png"
            when "Diners Club"
              @card_src = "diners.png"
            when "Discover"
              @card_src = "discover.png"
            end

            @exp_month = @customer_card.exp_month.to_s
            @exp_year = @customer_card.exp_year.to_s.slice(2,3)
          else
          end
        else
          redirect_to user_session_path, alert: "ログインしてください"
        end
      end
    end
  end

  def pay
    @images = @item.images.all

    if @item.buyer.present?
      redirect_to item_path(@item.id), alert: "売り切れています"
    else
      @item.with_lock do
        if current_user.creditcard.present?
          @card = Creditcard.find_by(user_id: current_user.id)
          Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)
          charge = Payjp::Charge.create(
            amount: @item.price,
            customer: Payjp::Customer.retrieve(@card.customer_id),
            currency: 'jpy'
          )
        else
          Payjp::Charge.create(
            amount: @item.price,
            card: params['payjp-token'],
            currency: 'jpy'
          )
        end
        @purchase = @item.update(buyer_id: current_user.id)
      end
    end
  end

  private
  def set_card
    @card = Creditcard.find_by(user_id: current_user.id)
  end

  def set_item
    @item = Item.find(params[:item_id])
  end
end

app/helpers/creditcards_helper.rb
module CreditcardsHelper
end

app/views/creditcards/_creditcard_information.html.haml
.creditcard__list
  .creditcard__list__title
    クレジットカード一覧
  .creditcard__list__frame
    .creditcard__info
      .creditcard__info__brand
        -# showメソッドで定義した@card_srcを呼び出し
        -# 画像をcardsというフォルダを作り、入れておく
        = image_tag "cards/#{@card_src}", class: "creditcard__info__brand__img", alt: @card_brand
      .creditcard__info__numbers
        .number
          -# Pay.jpから取得したカード番号の末尾４桁を取得
          = "**** **** **** " + @customer_card.last4
        .expiration__date
          .expiration__date__info
            -# showメソッドで定義した有効期限の年と月を取得
            = @exp_month + " / " + @exp_year
    .destroy__function
      .destroy__function__link
        -# 削除ボタンを作成、押すとdestroyメソッドが働くように
        = link_to creditcard_path, method: :delete, class: "destroy__function__link__btn" do 
          削除する
  .payment-details
    = link_to "支払い方法について >", "", class: "payment-details__btn"

app/views/creditcards/_registration_cardform.html.haml
-#form_tagメソッドでcreateアクションに入力情報を渡します。
= form_tag(creditcards_path, method: :post, id: "charge-form", class: "card__details", name: "inputForm") do
  .card__information
    .number-details
      .card-number カード番号
      %span.form-required 必須
    .number
      = text_field_tag 'payment_card_no', "", class: 'cardnumber', id: "payment_card_no", placeholder: '半角数字のみ', type: "text", maxlength: "16"
    -# 事前にassets/imagesにcardsファイルを作成、中に各カード会社の画像を入れておき、呼び出す。
    .cards__image
      = image_tag(image_path('cards/visa.png'), class: 'visa')
      = image_tag(image_path('cards/master.png'), class: 'master')
      = image_tag(image_path('cards/saison.png'), class: 'saison')
      = image_tag(image_path('cards/jcb.png'), class: 'jcb')
      = image_tag(image_path('cards/amex.png'), class: 'amex')
      = image_tag(image_path('cards/diners.png'), class: 'diners')
      = image_tag(image_path('cards/discover.png'), class: 'discover')


    .expirationdate
      .expirationdate__details
        .date 有効期限
        %span.form-required 必須
      .expirationdate__choice
        .month
          %select#payment_card_month.card-default{name: "payment_card_month", type: "text"}
            %option{value: "1"} 01
            %option{value: "2"} 02
            %option{value: "3"} 03
            %option{value: "4"} 04
            %option{value: "5"} 05
            %option{value: "6"} 06
            %option{value: "7"} 07
            %option{value: "8"} 08
            %option{value: "9"} 09
            %option{value: "10"} 10
            %option{value: "11"} 11
            %option{value: "12"} 12
          .month-details 月
        .year
          %select#payment_card_year.card-default{name: "payment_card_year", type: "text"}
            %option{value: "2020"} 20
            %option{value: "2021"} 21
            %option{value: "2022"} 22
            %option{value: "2023"} 23
            %option{value: "2024"} 24
            %option{value: "2025"} 25
            %option{value: "2026"} 26
            %option{value: "2027"} 27
            %option{value: "2028"} 28
            %option{value: "2029"} 29
            %option{value: "2030"} 30
          .year-details 年

    .securitycode
      .securitycode__details
        .securitycode__details__title セキュリティコード
        %span.form-required 必須
      .securitycode__cardsecurity
        = text_field_tag  "payment_card_cvc", "", type: 'text', class: 'securitycode__cardsecurity__form', id: "payment_card_cvc", maxlength: "4", placeholder: 'カード背面4桁もしくは3桁の番号'
      .card-question カード裏面の番号とは？
    .add 
      = submit_tag "登録する", class: "add__btn", id: "payment_card_submit-button"

app/views/creditcards/_registration_form.html.haml
-#form_tagメソッドでcreateアクションに入力情報を渡します。
= form_tag(creditcards_path, method: :post, id: "charge-form", class: "card__details", name: "inputForm") do
  .card__information
    .number-details
      .card-number カード番号
      %span.form-required 必須
    .number
      = text_field_tag 'payment_card_no', "", class: 'cardnumber', id: "payment_card_no", placeholder: '半角数字のみ', type: "text", maxlength: "16"
    -# 事前にassets/imagesにcardsファイルを作成、中に各カード会社の画像を入れておき、呼び出す。
    .cards__image
      = image_tag(image_path('cards/visa.png'), class: 'visa')
      = image_tag(image_path('cards/master.png'), class: 'master')
      = image_tag(image_path('cards/saison.png'), class: 'saison')
      = image_tag(image_path('cards/jcb.png'), class: 'jcb')
      = image_tag(image_path('cards/amex.png'), class: 'amex')
      = image_tag(image_path('cards/diners.png'), class: 'diners')
      = image_tag(image_path('cards/discover.png'), class: 'discover')


    .expirationdate
      .expirationdate__details
        .date 有効期限
        %span.form-required 必須
      .expirationdate__choice
        .month
          %select#payment_card_month.card-default{name: "payment_card_month", type: "text"}
            %option{value: "1"} 01
            %option{value: "2"} 02
            %option{value: "3"} 03
            %option{value: "4"} 04
            %option{value: "5"} 05
            %option{value: "6"} 06
            %option{value: "7"} 07
            %option{value: "8"} 08
            %option{value: "9"} 09
            %option{value: "10"} 10
            %option{value: "11"} 11
            %option{value: "12"} 12
          .month-details 月
        .year
          %select#payment_card_year.card-default{name: "payment_card_year", type: "text"}
            %option{value: "2020"} 20
            %option{value: "2021"} 21
            %option{value: "2022"} 22
            %option{value: "2023"} 23
            %option{value: "2024"} 24
            %option{value: "2025"} 25
            %option{value: "2026"} 26
            %option{value: "2027"} 27
            %option{value: "2028"} 28
            %option{value: "2029"} 29
            %option{value: "2030"} 30
          .year-details 年

    .securitycode
      .securitycode__details
        .securitycode__details__title セキュリティコード
        %span.form-required 必須
      .securitycode__cardsecurity
        = text_field_tag  "payment_card_cvc", "", type: 'text', class: 'securitycode__cardsecurity__form', id: "payment_card_cvc", maxlength: "4", placeholder: 'カード背面4桁もしくは3桁の番号'
      .card-question カード裏面の番号とは？
    .add 
      = submit_tag "登録する", class: "add__btn", id: "payment_card_submit-button"

app/views/creditcards/buy.html.haml
.form-buy
  .buy__header
    = render "items/form_header"
  - if @user.creditcard.present?
    .buy
      %section.buy__title
        %h2.buy__title__name 購入内容の確認

      %section.buy__item
        .buy__item__info
          .buy__item__info__image
            = image_tag  @item.images[0].image.url, class:"item-image"

          .buy__item__info__details
            .item__name 【美品】master card
            %p.item__price
              %span.price
                = "#{@item.price}" + "円"
              %span.shipping__fee （税込）送料込み

      %section.buy__content
        .buy__content__price
          %span.purchase-price 支払い金額
          %span.price
          = "¥" + "#{@item.price}"


      %section.buy__creditcard
        .buy__creditcard__method
          %h3.method-howto 支払い方法
          =link_to "変更する", new_creditcard_url, class: "method-change"
        .buy__creditcard__registration
          %p クレジットカード
          %p 
          = "**** **** **** " + @customer_card.last4
          %p 
          有効期限
          = @exp_month + " / " + @exp_year
          .bcr-card
            = image_tag "cards/#{@card_src}", class:"bcr-card"

      %section.buy__shipping
        .buy__shipping__destination
          %h3.shipping-destination 配送先
          =link_to "変更する", '#', class: "method-change"
        .buy__shipping__address
          %p
            = @address.post_number.to_s.slice(0,3) + " -"
            = @address.post_number.to_s.slice(3,4)
          %p
            = @address.prefecture
            = @address.city
            = @address.address
            = @address.apartment
          %p
            = @address.lastname
            = @address.firstname

      %section.buy__btn
        .buy__btn__content
          %p.buy__btn__content__notification
          郵便局/コンビニ受取をご希望の方は、購入後に
          %b.buy__btn__content__notification__bold 取引画面
          から受取場所を変更をすることが可能です。出品者が発送作業を開始した後は受取場所の変更ができませんので、早めに変更を行ってください。
          .buy__btn__button
            = link_to "購入する", pay_item_creditcards_path(item_id: @item.id), method: :post, class: "btn--purchase__btn"
  - else
    .buy
      %section.buy__title
        %h2.buy__title__name 購入内容の確認

      %section.buy__item
        .buy__item__info
          .buy__item__info__image
            = image_tag  @item.images[0].image.url, class:"item-image"

          .buy__item__info__details
            .item__name 【美品】master card
            %p.item__price
              %span.price
                = "#{@item.price}" + "円"
              %span.shipping__fee （税込）送料込み

      %section.buy__content
        .buy__content__price
          %span.purchase-price 支払い金額
          %span.price
          = "¥" + "#{@item.price}"


      %section.buy__creditcard
        .buy__creditcard__method
          %h3.method-howto 支払い方法
          =link_to "クレジットカードを追加する", new_creditcard_url, class: "method-change"

      %section.buy__shipping
        .buy__shipping__destination
          %h3.shipping-destination 配送先
          =link_to "変更する", '#', class: "method-change"
        .buy__shipping__address
          %p
            = @address.prefecture
            = @address.city
            = @address.address
            = @address.apartment
          %p
            = @address.lastname
            = @address.firstname

      %section.buy__btn
        .buy__btn__content
          %p.buy__btn__content__notification
          郵便局/コンビニ受取をご希望の方は、購入後に
          %b.buy__btn__content__notification__bold 取引画面
          から受取場所を変更をすることが可能です。出品者が発送作業を開始した後は受取場所の変更ができませんので、早めに変更を行ってください。
          .buy__btn__button

        %section.buy__btn
          .buy__btn__none
            = form_tag(action: :pay, method: :post) do
              %script.payjp-button{src: "https://checkout.pay.jp", type: "text/javascript" ,"data-text": "購入する" ,"data-key": "pk_test_1ec0ec04db6b232048c16e77",}

  .buy__footer
    = render "items/form_footer"

app/views/creditcards/create.html.haml
.form-card_create
  .card-create__header
  = render "items/form_header"

  .crc__create
    .crc__create__frame
      .crc__create__frame__message
        登録が完了しました。
      %ul.crc__create__frame__btns
        -# マイページに戻るパスを指定
        %li.crc__my_page_link
          = link_to "マイページに戻る", user_path(current_user.id), class: "my_page_link__btn"
        -# のちに実装する、登録クレジットカード詳細表示(showアクション)に行くパスを指定
        %li.crc__credit_cards_index_link
          = link_to "登録カード一覧", creditcard_path(current_user.id), class: "credit_cards_index_link__btn"

app/views/creditcards/new.html.haml
.form-card
  .card__header
  = render "items/form_header"

  .card
    %section.card__title
      %h2.card__title__name 支払い方法
      = render "registration_cardform"


  .card__fotter
    = render "items/form_footer"

app/views/creditcards/pay.html.haml
.form-card
  .card__header
  = render "items/form_header"

  .pay
    .pay__contents
      .pay__details
        .pay__details__message
          購入が完了しました。
      %ul.purchased__links
        %li.purchased__links__TopPage
          = link_to "トップページに戻る", root_path, class: "purchased__links__TopPage__btn"
        %li.purchased__links__index
          = link_to "購入商品一覧", "#", class: "purchased__links__index__btn"
  .card__fotter
  = render "items/form_footer"

app/views/creditcards/show.html.haml
.form-card
  .card__header
  = render "items/form_header"

  .card
    %section.card__title
      %h2.card__title__name クレジットカード情報
    = render "creditcard_information"
  
  .card__fotter
    = render "items/form_footer"