config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  devise_scope :user do
    get  'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  root "items#index"

  resources :users, only: [:show] do
    get 'logout', to: 'users#logout'
    get 'items', to: 'users#items'
    resources :cards, only: [:new, :index, :show] do
      collection do
      # クレジットカード登録
        # post 'pay', to: 'cards#pay'
      # クレジットカード削除
        # delete 'delete', to: 'cards#delete'
      end
    end
  end

  resources :items do
    collection do
      get "get_shipping_way"
      get "category_children"
      get "category_grandchildren"
      get "get_size", defauts: { format: 'json' }
    end
  end


  resources :brands, only: [:index], defaults: {format: 'json'}

  resources :items do
    resource :creditcards do
      member do
        get "buy"
        post "pay"
      end
    end
  end
  resources :creditcards, only: [:new, :create, :destroy, :show]

end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions

  belongs_to              :seller         ,class_name: "User"
  has_many                :images         ,dependent: :destroy
  belongs_to              :category
  belongs_to              :brand          ,optional: true
  belongs_to              :buyer          ,class_name: "User", optional: true
  # has_many                :favorites      ,dependent: :destroy
  # has_many                :evaluations
  # has_many                :comments       ,dependent: :destroy
  belongs_to_active_hash  :condition
  belongs_to_active_hash  :shipping_fee
  belongs_to_active_hash  :prefecture
  belongs_to_active_hash  :shipping_period
  belongs_to_active_hash  :shipping_way
  belongs_to_active_hash  :size
  belongs_to_active_hash  :status

  # fields_forメソッドを利用する際に、親モデルの中に書く必要があるメソッド
  # 引数として、子モデルの名前を記載する。
  # allow_destroy: trueで、親のレコードが削除された場合に、関連付いている子のレコードも一緒に削除できる。
  accepts_nested_attributes_for :images, allow_destroy: true
  validates :images, :name, :introduction, :price, :category_id, :seller_id, :condition_id, :size, :shipping_fee_id, :prefecture_id, :shipping_period_id, :shipping_way_id, :status_id, presence: true
  validates :price, numericality: { only_integer: true, greater_than: 0, less_than: 9999999 }
  validates :name, length: { maximum: 40 }
  validates :introduction, length: { maximum: 1000 }
# 一つ前のidのレコードを持ってくるメソッド
  def previous
    Item.where('id < ?', id).order("id asc").last
  end
# 一つ先のidのレコードを持ってくるメソッド
  def next
    Item.where("id > ?", id).order("id asc").first
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :destroy, :edit, :update]

  def index
    @items = Item.includes(:images).where(buyer_id: nil).order("id desc").first(4)
    @items_ladies = Item.includes(:images).where(category_id: 1..198, buyer_id: nil).order("id desc").first(4)
    @items_mens = Item.includes(:images).where(category_id: 199..343, buyer_id: nil).order("id desc").first(4)
    @items_chanel = Item.includes(:images).where(brand_id: [2447,8386,11784,12827,13628], buyer_id: nil).order("id desc").first(4)
  end

  def new
    @item = Item.new
    # itemクラスのインスタンスに関連づけられたImageクラスのインスタンスを作成
    @item.images.build
    @category = Category.where(ancestry: nil).order("id ASC")
  end

  def create
    @item = Item.new(item_params)
    @category = Category.all
    if @item.save
      redirect_to root_path
    else
      redirect_to new_item_path, notice: "出品できません。入力必須項目を確認してください"
    end
  end

  def edit
    if @item.seller_id == current_user.id
      @category = Category.where(ancestry: nil).order("id ASC")
      if @item.brand_id.present?
        @brand = @item.brand.name
      else
        @brand = ""
      end
    else
      redirect_to root_path, notice: "あなたが出品した商品ではないので編集できません"
    end
  end
  
  def update
    if @item.update(item_params)
      redirect_to root_path
    else
      redirect_to edit_item_path, notice: "編集できません。入力必須項目を確認してください"
    end
  end

  def show
    @images = @item.images
  end

  def destroy
    if @item.seller_id == current_user.id && @item.destroy
      redirect_to root_path
    else
      flash.now[:alert] = '削除に失敗しました'
      render :show
    end
  end

  
  def get_shipping_way
    @shipping_way = ShippingWay.find_all_by_group(params[:selected_fee])
  end
  
  def category_children
    @category_children = Category.find(params[:category_id]).children
  end

  def category_grandchildren 
    @category_grandchildren = Category.find(params[:child_id]).children
  end

  def get_size
    select_grandchild = Category.find("#{params[:grandchild_id]}") #孫カテゴリーを取得
    if related_size_parent = select_grandchild.sizes[0]#孫カテゴリーの紐づくサイズ(親)があれば取得
      @sizes = related_size_parent.children#紐づいたサイズ(親)の子供の配列を取得
    else
      select_child = Category.find("#{params[:grandchild_id]}").parent #孫カテゴリーの親を取得
      if related_size_parent = select_child.sizes[0] #孫カテゴリーの親と紐づくサイズ(親)があれば取得
        @sizes = related_size_parent.children #紐づいたサイズ(親)の子供の配列を取得
      end
    end
  end

  private
  def item_params
  # fields_forを利用して作成されたフォームから来る値は、○○s_attributes: [:××]という形でparamsに入る
  # fields_forから送られてくるこのキーを持った情報を頼りに、railsが子モデルの更新・削除を行う
    params.require(:item).permit(
      :name,
      :introduction,
      :category_id,
      :size_id,
      :brand_id,
      :condition_id,
      :shipping_fee_id,
      :shipping_way_id,
      :prefecture_id,
      :shipping_period_id,
      :price,
      images_attributes: [:image, :id, :_destroy]
      ).merge( seller_id: current_user.id)
  end


  def set_item
    @item = Item.find(params[:id])
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_footer.html.haml
.contents
  .content
    %ul.list
      %li.title
        FURIMAについて
      %li.text
        = link_to "会社概要（運営会社）", "/", class: "footer-content"
      %li.text
        = link_to "プライバシーポリシー", "/", class: "footer-content"
      %li.text
        = link_to "FURIMA利用規約", "/", class: "footer-content"
      %li.text
        = link_to "ポイントに関する特約", "/", class: "footer-content"
  .content
    %ul.list
      %li.title
        FURIMAを見る
      %li.text
        = link_to "カテゴリー一覧", "/", class: "footer-content"
      %li.text
        = link_to "ブランド一覧", "/", class: "footer-content"
  .content
    %ul.list
      %li.title
        ヘルプ＆ガイド
      %li.text
        = link_to "FURIMAガイド", "/", class: "footer-content"
      %li.text
        = link_to "FURIMAロゴ利用ガイドライン", "/", class: "footer-content"
      %li.text
        = link_to "お知らせ", "/", class: "footer-content"
.logo
  =image_tag 'material/logo/logo-white.png', alt: 'ロゴ', class: "footer-logo"
  %p.sign
    ©︎FURIMA

app/views/items/_form_footer.html.haml
.form-footer
  .form-footer--contents
    %ul.contents-links
      %li
        = link_to "#", class: "contents-links--item" do
          プライバシーポリシー
      %li
        = link_to "#", class: "contents-links--item" do
          FURIMA利用規約
      %li
        = link_to "#", class: "contents-links--item" do
          特定商取引に関する表記
    = link_to image_tag("material/logo/logo-white.png", alt: "FURIMA", size: "100x40"), "/"
    %P.form-footer--contents__trademark
      ©️ FURIMA

app/views/items/_form_header.html.haml
.form-header
  .form-header__bar
    = link_to image_tag("material/logo/logo.png", alt: "FURIMA", size: "185x49", class: "logo"), "/"

app/views/items/_form_menu.html.haml
.form-body
  .form-items
    = form_with model: @item, local: true do |f|
      = render 'layouts/error-messages'
      .photos
        .photos--title
          %h3
            出品画像
            %span.form-required 必須
          %p.photos--title__comments
            最大10枚までアップロードできます
        .photos-box
          .previews
            - if @item.persisted?
              - @item.images.each_with_index do |image, i|
                .preview
                  = image_tag image.image.url, width: "105px", height: "90px", data: { index: i }
                  .js-btn
                    .edit-btn
                      %label{for: "item_images_attributes_#{i}_image"}
                        %span
                          編集
                    .js-remove{:id => "delete-btn-#{i}"}
                      削除
          - if @item.images.count < 10
            .label-content
              %label.photos--drops{for: "item_images_attributes_#{@item.images.count}_image"}
                %i.fas.fa-camera
                  .photos--drops__comment
                    %p
                      クリックしてファイルをアップロード
          .hidden-content
            = f.fields_for :images do |i|
              .js-file_group{data: {index:  "#{i.index}"}}
                = i.file_field :image, class: 'photos--form', accept: 'image/png,image/jpeg'
                = i.check_box :_destroy, { class: "hidden"}
            - if @item.persisted?
              .js-file_group{data: {index:  "#{@item.images.count}"}}
                = file_field_tag :image, name: "item[images_attributes][#{@item.images.count}][image]", class: "photos--form", id:"item_images_attributes_#{@item.images.count}_image"

      .items
        .items--name.contents-height
          %h3
            商品名
            %span.form-required 必須
          = f.text_field :name, { class: 'items-name-box', placeholder: '40文字まで' }
        .items--text
          %h3
            商品の説明
            %span.form-required 必須
          = f.text_area :introduction, { class: 'items--text__field js-text', placeholder: '商品の説明（必須 1,000文字以内）（色、素材、重さ、定価、注意点など）例）2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。', rows: '5' }
          %p.items--text__count

      .items-data
        %p
          商品の詳細
        .items-data--category
          %h3
            カテゴリー
            %span.form-required 必須
          -if @item.persisted? 
            .items-data--category--edit
              .items-data--category__select
                = f.collection_select :category, @category, :id, :name, { prompt: "選択してください", selected: @item.category.parent.parent_id }, {class: "select-box", id: "parent_category_edit"}
              .items-data--category__child#children_wrapper_edit
                = f.collection_select :category, @item.category.parent.parent.children, :id, :name, { prompt: "選択してください", selected: @item.category.parent_id }, {class: "select-box", id: "child_category_edit"}
              .items-data--category__grandchild#grandchildren_wrapper_edit
                = f.collection_select :category, @item.category.parent.children, :id, :name, { prompt: "選択してください", selected: @item.category.id }, {class: "select-box", id: "grandchild_category_edit", name: "product[category_id]" }
            -if @item.size.name != ""
              .items-data--category__size_wrapper
                %label.items-data--size
                  サイズ
                  %span.form-required 必須
                = f.collection_select :size, @item.size.parent.children, :id, :name, { prompt: "選択してください", selected: @item.size_id }, {class: "select-box", id: "size_wrapper_edit"}  
          - else
            .items-data--category__select
              = f.collection_select :category, @category, :id, :name, { prompt: "選択してください"}, {class: "select-box", id: "category_select" }
            .items-data--category__child

        .items-data--barand
          %h3
            ブランド
            %span.form-any 任意
          -if @item.persisted?
            = f.text_field :brand_id, { class: 'items-name-box', value: @brand }
          -else
            = f.text_field :brand_id, { class: 'items-name-box', placeholder: '例）シャネル' }
          #brand-search-result 
        .items-data--status.contents-height
          %h3
            商品の状態
            %span.form-required 必須
          = f.collection_select :condition_id, Condition.all, :id, :name, {include_blank: '選択してください'}, {class: "select-box"}
          -# { include_blank: '選択してください' }にすると、この選択肢が表示されているときは何も選択されていないことになる。
          
      .delivery
        %p.p-title
          配送について
          = link_to '?', '#', target: '_blank', class: 'p-title--question'
        .delivery--charges.contents-height
          %h3
            配送料の負担
            %span.form-required 必須
          - if @item.persisted? 
            = f.collection_select :shipping_fee_id, ShippingFee.all, :id, :name, {include_blank: '選択してください', selected: @item.shipping_fee.id }, {class: "select-box", id: "shipping-fee_select" }
          - else
            = f.collection_select :shipping_fee_id, ShippingFee.all, :id, :name, {include_blank: '選択してください'}, {class: "select-box", id: "shipping-fee_select" }
        .delivery--way.contents-height
          - if @item.persisted?
            .product-select-wrapper#shipping-way_wrapper
              %h3
                配送方法
                %span.form-required 必須
              = f.collection_select :shipping_way_id, ShippingWay.where(group: @item.shipping_fee_id.to_s), :id, :name, {include_brank: '選択してください', selected: @item.shipping_way.id }, {class: "select-box", id: "shipping-way_select"}
        .delivery--area.contents-height
          %h3
            発送元の地域
            %span.form-required 必須
          = f.collection_select :prefecture_id, Prefecture.all, :id, :name, {include_blank: '選択してください'}, {class: "select-box"}
        .delivery--day.contents-height
          %h3
            発送までの日数
            %span.form-required 必須
          = f.collection_select :shipping_period_id, ShippingPeriod.all, :id, :name, {include_blank: '選択してください'}, {class: "select-box"}

      .cost
        %p.p-title
          価格（¥300〜9,999,999）
          = link_to '?', '#', target: '_blank', class: 'p-title--question'
        .cost--selling
          .cost--selling__price
            %h3
              販売価格
              %span.form-required 必須
          -if @item.persisted?
            .cost--selling--number
              = f.number_field :price, {  class: 'cost--selling--number__price', value: @item.price, style: 'text-align:right'} 
          -else
            .cost--selling--number
              %p ¥
              = f.number_field :price, {  class: 'cost--selling--number__price', placeholder: '0', style: 'text-align:right', value: number_with_delimiter(@price, precision: 3)} 
        .cost--commission
          %p 販売手数料 (10%)
          %span.gain-commission -
        .cost--profit
          %p 販売利益
          -# = f.number_field :price, style: "display: none", id: "price"

          %span.gain-profit -

      .btns
        = f.button '出品する', class: 'btns--display btn-design'
        = f.button '下書きに保存', class: 'btns--draft btn-design'  
        = link_to "/", class: "btns--return" do
          もどる
        
      .notes
        %p
          禁止されている
          = link_to '行為', '#', target: '_blank', class: 'notes--content'
          および
          = link_to '出品物', '#', target: '_blank', class: 'notes--content'
          を必ずご確認ください。
          = link_to '偽ブランド品', '#', target: '_blank', class: 'notes--content'
          や
          = link_to '盗品物', '#', target: '_blank', class: 'notes--content'
          などの販売は犯罪であり、法律により処罰される可能性があります。また、出品をもちまして
          = link_to '加盟店規約', '#', target: '_blank', class: 'notes--content'
          に同意したことになります。

app/views/items/_header.html.haml
.header__contents
  .header__contents__main
    .header__contents__main__main-title
      = link_to image_tag("material/logo/logo.png", class:"icon"), "/" 
    .header__contents__main__search-box
      = form_with url: "#", method: :get, local: true do |f|
        = f.text_field :search, class: "input-box", placeholder:"キーワードから探す"
        %button{type: "submit", class:"search-btn"} 
          = image_tag 'icon-search1.png',class: "image"

  .header__contents__navbar
    %ul.list-left
      %li.list-left__category-btn 
        = link_to "カテゴリー", "/", class: "list-btn"
      %li.list-left__brand-btn
        = link_to "ブランド", "/", class: "list-btn"

      %ul.list-right
        - if user_signed_in?  
          =link_to "/users/#{current_user.id}", class: "list-btn" do 
            マイページ
        - else
          = link_to new_user_session_path, class:"list-btn " do
            ログイン
          = link_to new_user_registration_path, class:"list-btn2 " do
            新規会員登録      
        

app/views/items/_hierarchy.html.haml
%ul
  %li
    =link_to '#' do
      FURIMA
  %li
    = icon('fa', 'angle-right') 
  %li
    =link_to '#' do
      レディース
  %li
    = icon('fa', 'angle-right') 
  %li
    =link_to '#' do
      トップス
  %li
    = icon('fa', 'angle-right') 
  %li
    =link_to '#' do
      Tシャツ/カットソー(半袖/袖なし)
  %li
    = icon('fa', 'angle-right') 
  %li.hierarchy__current
    %span ああああ

app/views/items/_item.html.haml
=link_to item_path(item.id) do
  .main__pickup__contents__items__item
    .main__pickup__contents__items__item__image
      = image_tag item.images.first.image.url, class:"pickup-item"
    .main__pickup__contents__items__item__info
      %h3.name
        = item.name
      .main__pickup__contents__items__item__info__detail
        %ul
          %li
            = item.price.to_s + "円"
          %li
            = icon('fa', 'star')
            0
        %p (税込)

app/views/items/_kategory-hierarchy.html.haml
-# 上部のカテゴリ階層表示
%nav.kategory-hierarchy
  %ul
    %li
      =link_to '#' do
        FURIMA
    %li
      = icon('fa', 'angle-right') 
    %li
      =link_to '#' do
        レディース
    %li
      = icon('fa', 'angle-right') 
    %li
      =link_to '#' do
        トップス
    %li
      = icon('fa', 'angle-right') 
    %li
      =link_to '#' do
        Tシャツ/カットソー(半袖/袖なし)
    %li
      = icon('fa', 'angle-right') 
    %li.kategory-hierarchy__current
      %span ああああ

app/views/items/_purchasebtn.html.haml
-# 画面右下の固定アイコン

- if user_signed_in?
  =link_to new_item_path do
    .purchaseBtn
      %span.purchaseBtn__text 出品する
      = image_tag "icon_camera.png", class: "purchaseBtn-icon"
- else
  =link_to user_session_path do
    .purchaseBtn
      %span.purchaseBtn__text 出品する
      = image_tag "icon_camera.png", class: "purchaseBtn-icon"

app/views/items/_third-section.html.haml
.third-section
  .third-section__content
    .third-section__content__sub-message
      だれでもかんたん、人生を変えるフリマアプリ
    .third-section__content__main-message
      今すぐ無料ダウンロード！
    .third-section__content__btn
      = image_tag "material/logo/app_store_badge_US-UK_RGB_blk_092917.svg", class: "btn_a"
      = image_tag "material/logo/google-play-badge.png", class: "btn_g"

app/views/items/edit.html.haml
.form-new
  = render "form_header"
  = render "form_menu"
  = render "form_footer"

app/views/items/index.html.haml
-# ヘッダー
%header
  = render 'header'

.main
  -# ファーストビュー
  .main__fv-section
    %h1.main__fv-section__title 人生を変えるフリマアプリ
    %p.main__fv-section__text 
      FURIMAはだれでもかんたんに出品・購入できる
      %br
      フリマアプリです
    .main__fv-section__btn
      = image_tag "material/logo/app_store_badge_US-UK_RGB_blk_092917.svg", class: "btn_a"
      = image_tag "material/logo/google-play-badge.png", class: "btn_g"


  -# FURIMAが選ばれる3つの理由
  .main__introduction
    .main__introduction__title
      FURIMAが選ばれる3つの理由
    %ul.main__introduction__contents
      %li.main__introduction__contents__content
        .main__introduction__contents__content__image
          = image_tag "material/pict/pict-reason-01.jpg", class:"list-image"
          .main__introduction__contents__content__image__number 1
        .main__introduction__contents__content__title 
          %span.span 3分
          ですぐに出品
        .main__introduction__contents__content__text 
          スマホで入力するだけで簡単に出品できる！

      %li.main__introduction__contents__content
        .main__introduction__contents__content__image
          = image_tag "material/pict/pict-reason-02.jpg", class:"list-image"
          .main__introduction__contents__content__image__number 2
        .main__introduction__contents__content__title 
          %span.span シンプル
          で使いやすい
        .main__introduction__contents__content__text 
          めんどくさい入力は必要なく、検索も購入もスムーズ！

      %li.main__introduction__contents__content--last
        .main__introduction__contents__content__image
          = image_tag "material/pict/pict-reason-03.jpg", class:"list-image"
          .main__introduction__contents__content__image__number 3
        .main__introduction__contents__content__title 
          手数料
          %span.span 業界最安
        .main__introduction__contents__content__text 
          最大3%でお得に出品＆購入！


  -# セカンドビュー
  .main__middle-section
    .main__middle-section__content
      .main__middle-section__content__subtitle
        会員数日本一位
      .main__middle-section__content__text
        FURIMAは、フリマアプリで最も人気。
        %br
        出品・購入回数も業界最多です！
        %br
        欲しかったあの商品に出会えるかもしれません。
      .main__middle-section__content__btn
        = image_tag "material/logo/app_store_badge_US-UK_RGB_blk_092917.svg", class: "btn_a"
        = image_tag "material/logo/google-play-badge.png", class: "btn_g"


  -# FURIMAの特徴
  .main__app-feature
    .main__app-feature__title
      FURIMAの特徴
    %ul.main__app-feature__lists
      -# 特徴その1
      %li.main__app-feature__lists__content
        .main__app-feature__lists__content__image
          = image_tag "material/icon/icon-01.png", class:"list-image"
        .main__app-feature__lists__content__title
          簡単に売り買いできる
        .main__app-feature__lists__content__text
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      -# 特徴その2
      %li.main__app-feature__lists__content
        .main__app-feature__lists__content__image
          = image_tag "material/icon/icon-03.png", class:"list-image"
        .main__app-feature__lists__content__title
          売上金は即日振込みに対応
        .main__app-feature__lists__content__text
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします！
      -# 特徴その3
      %li.main__app-feature__lists__content
        .main__app-feature__lists__content__image
          = image_tag "material/icon/icon-04.png", class:"list-image"
        .main__app-feature__lists__content__title
          様々な支払いに対応
        .main__app-feature__lists__content__text
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。


  -# ピックアップカテゴリー
  .main__pickup
    .main__pickup__title
      ピックアップカテゴリー
    .main__pickup__contents
      .main__pickup__contents__title
        =link_to "新規投稿商品","/",class:"pickup-title"
      .main__pickup__contents__items
        = render partial: 'item', collection: @items
    .main__pickup__contents
      .main__pickup__contents__title
        =link_to "レディース","/",class:"pickup-title"
      .main__pickup__contents__items
        = render partial: 'item', collection: @items_ladies
    .main__pickup__contents
      .main__pickup__contents__title
        =link_to "メンズ","/",class:"pickup-title"
      .main__pickup__contents__items
        = render partial: 'item', collection: @items_mens


  -# ピックアップブランド
  .main__pickup
    .main__pickup__title
      ピックアップブランド
    .main__pickup__contents
      .main__pickup__contents__title
        = link_to "シャネル","/",class:"pickup-title"
        .main__pickup__contents__items
          = render partial: 'item', collection: @items_chanel

  -# サードビュー
  .main__third-section
    = render 'third-section'


-# フッター
%footer
  = render 'footer'



-# 画面右下の固定アイコン
= render 'purchasebtn'

app/views/items/new.html.haml
.form-new
  = render "form_header"
  = render "form_menu"
  = render "form_footer"

app/views/items/show.html.haml
%header
  = render partial: 'header'
.under-header
  = render partial: 'kategory-hierarchy'
.item-wrapper
  .item-box
    %h1.item-box__name
      = @item.name
    .item-box__image
      %ul.item-box__image__main
        %li.item-box__image__main__pict.item
          = image_tag @item.images.first.image.url, class:"resize"
      %ul.item-box__image__sub
        - @item.images.each do |image|
          %li.item-box__image__sub__pict
            = image_tag image.image.url, class:"resize"
    .item-box__price
      %span ¥
      %span
        = @item.price
      .item-box__price__detail （税込）送料別
    .item-box__introduction
      = simple_format(@item.introduction)
    .item-box__table
      %table
        %tr
          %th 出品者
          %td
            = @item.seller.nickname
        %tr
          %th カテゴリー
          %td 
            -# カテゴリを親、その親まで表示させる
            - if @item.category.parent.parent
              =link_to '#', class:"item-box__table__link" do
                = @item.category.parent.parent.name
              %br
            - if @item.category.parent
              =link_to '#', class:"item-box__table__link" do
                = @item.category.parent.name
              %br
            =link_to '#', class:"item-box__table__link" do
              = @item.category.name
        %tr
          %th ブランド
          %td
            - if @item.brand
              = @item.brand.name
        %tr
          %th 商品のサイズ
          %td
            = @item.size.name
        %tr
          %th 商品の状態
          %td
            = @item.condition.name
        %tr
          %th 配送料の負担
          %td
            = @item.shipping_fee.name
        %tr
          %th 配送方法
          %td
            = @item.shipping_way.name
        %tr
          %th 発送元の地域
          %td
            =link_to '#', class:"item-box__table__link" do
              = @item.prefecture.name
        %tr
          %th 発送日の目安
          %td
            = @item.shipping_period.name
    .option-box
      =link_to '#', class: 'option-box__favorite' do
        = icon('fa', 'star', class: 'option-box__favorite__icon')
        お気に入り 0
      =link_to '#', class: 'option-box__report' do
        = icon('fas', 'flag', class: 'option-box__report__icon')
        不適切な商品の通報
  -# 編集・削除は出品者のみ表示・出品中のみ表示
  - if user_signed_in? && current_user.id == @item.seller_id && @item.status_id == 1
    .seller-box
      .seller-box__edit
        = link_to edit_item_path(@item), class:"seller-box__edit--btn" do
          編集する
        %span or
      .seller-box__delete
        = link_to item_path(@item), method: :delete, class:"seller-box__delete--btn" do
          削除
  .comment-box
    %form.comment-form
      %textarea.comment-form__content
      .comment-form__note
        %span 相手のことを考え丁寧なコメントを心がけましょう。
        %br
        %span 不快な言葉遣いなどは利用制限や退会処分となることがあります。
      %button.comment-form__button 
        = icon('fas', 'comment')
        コメントする
  .links
    %ul.links__around
      - unless Item.first.id == @item.id
        %li
          =link_to item_path(@item.previous.id), class:"links__around__link" do
            = icon('fa', 'angle-left', class:"links__around__link__icon") 
            前の商品
      - unless Item.last.id == @item.id
        %li
          =link_to item_path(@item.next.id), class:"links__around__link" do
            後ろの商品 
            = icon('fa', 'angle-right', class:"links__around__link__icon")
    .links__kategory
      -# カテゴリの最上位へのリンクを表示させる
      - if @item.category.parent.parent
        =link_to '#', class:"links__kategory__link" do
          = @item.category.parent.parent.name + "をもっと見る"
      - elsif @item.category.parent
        =link_to '#', class:"links__kategory__link" do
          = @item.category.parent.name + "をもっと見る"
      - else
        =link_to '#', class:"links__kategory__link" do
          = @item.category.name + "をもっと見る"
          
-# 出品者の場合または出品中でない場合は購入ボタンの表示はしない
-# ログインしていない場合はログインページへ遷移させる
- if user_signed_in?
  - if current_user.id == @item.seller_id || @item.status_id != 1
  - else
    =link_to buy_item_creditcards_path(item_id: @item.id) do
      .purchaseBtn.purchaseBtn--buy
        %span.purchaseBtn__text 購入する
        =icon('fas', 'wallet', class:"purchaseBtn--icon-wallet")
- else
  =link_to user_session_path do
    .purchaseBtn.purchaseBtn--buy
      %span.purchaseBtn__text 購入する
      =icon('fas', 'wallet', class:"purchaseBtn--icon-wallet")
.over-footer
  = render partial: 'third-section'
%footer
  = render partial: 'items/footer'